### ISSUE TITLE
Karma and Todos for Daniel Shames

### ISSUE THREAD

**Issue by zvili** [TechnionYP5777/SmartCity-ParkingManagement#15]
_From @dshames on November 7, 2016 13:53_

- [x]  Use a picture, photo or distinct, familiar, personal 
avatar. Don't use an automatic icon (we need this to be able to identify you in the tens of students we have):
- [x] Present yourself by a not too rude **nick**  
- [x]  Describe yourself in the bio page; FYI, here is my description:
- [x]  State that you are (not) in search for a job, i.e., mark, or unmark this box:

_Copied from original issue: SpartanRefactoring/Spartanizer#790_

**Comment by zvili** [comment]
_From @dshames on November 7, 2016 13:54_

@yossigil Done.

**Comment by zvili** [comment]
_From @yossigil on November 10, 2016 12:50_

Make sure you use lables and milestone. Bad karma for starting TDD without a TODO page.

**Comment by zvili** [comment]
_From @yossigil on November 17, 2016 20:5_

@AdiOmari : 
He did not place a milestone.
fixed it.

**Comment by zvili** [comment]
_From @AdiOmari on November 17, 2016 20:9_

👍

**Comment by dshames** [comment]
As agreed, I'm posting here the current issues I'm assigned on: #36 , #41 .
I'm in charge of issues #36 and #41 .

**Comment by yossigil** [comment]
:+1:

**Comment by dshames** [comment]
I  already learned how to use some of the Google Maps API functionalities.

**Comment by yossigil** [comment]
`I already learned how to use some of the Google Maps API functionalities.`

This does not count, since there is no issue.

**Comment by dshames** [comment]
This is part of finding the closest parking area. Should I edit the relevant issue? Or create a new issue?

**Comment by yossigil** [comment]
I do not know how to help. If you did issues, mark them. If you did not, what shoudl **I** do?

**Comment by orimarco** [comment]
How would you rank your amount of contribution to the project compared to others in the group?
Please specify the ordinal of the **quintile**.

**Comment by dshames** [comment]
@orimarco I can't compare myself to my other team members. Everybody works just fine and does his job. I had some problems with my vm so I had trouble pushing my progress. However, everything is fine now and I pushed some of my recent work.

**Comment by yossigil** [comment]
@dshames 
OOPS, you forgot to make a list of issues you finished during the first sprint, why won't you make it?

**Comment by orimarco** [comment]
@dshames feel free to ignore 😄

**Comment by dshames** [comment]
@yossigil I'm currently working on issues #36 and #41 . Both issues require a bit more work, will update when I'm finished. You can check my work on the Navigation class.

**Comment by yossigil** [comment]
issues in previous sprint?

**Comment by dshames** [comment]
Just did a wiki page about the google maps api at #74 .
I also finished writing the code for issues #36 and #41 , I will close both issues in the following days after testing all the functions.

**Comment by dshames** [comment]
@yossigil In the firs Sprint, @DavidCohen55 and I translated (and attended) a preparation meeting at the 21.11 #17 . I also attneded another group meeting at the first of December #19 .

**Comment by yossigil** [comment]
ok. 

@zvili  @idabran : 
we need to make sure that everyone were pulling their weight in this team and that load is balanced

**Comment by dshames** [comment]
finished #36 and #41 . my next issue will be #82

**Comment by dshames** [comment]
finished #82 . my next issue will be #90

**Comment by dshames** [comment]
continuing to #92

**Comment by dshames** [comment]
finished #92 , #100 , #101
